// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: api/gpt/gpt.proto

package gpt

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindBankInformationResponse_Contacts_Type int32

const (
	FindBankInformationResponse_Contacts_PHONE FindBankInformationResponse_Contacts_Type = 0
	FindBankInformationResponse_Contacts_EMAIL FindBankInformationResponse_Contacts_Type = 1
)

// Enum value maps for FindBankInformationResponse_Contacts_Type.
var (
	FindBankInformationResponse_Contacts_Type_name = map[int32]string{
		0: "PHONE",
		1: "EMAIL",
	}
	FindBankInformationResponse_Contacts_Type_value = map[string]int32{
		"PHONE": 0,
		"EMAIL": 1,
	}
)

func (x FindBankInformationResponse_Contacts_Type) Enum() *FindBankInformationResponse_Contacts_Type {
	p := new(FindBankInformationResponse_Contacts_Type)
	*p = x
	return p
}

func (x FindBankInformationResponse_Contacts_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FindBankInformationResponse_Contacts_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_api_gpt_gpt_proto_enumTypes[0].Descriptor()
}

func (FindBankInformationResponse_Contacts_Type) Type() protoreflect.EnumType {
	return &file_api_gpt_gpt_proto_enumTypes[0]
}

func (x FindBankInformationResponse_Contacts_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FindBankInformationResponse_Contacts_Type.Descriptor instead.
func (FindBankInformationResponse_Contacts_Type) EnumDescriptor() ([]byte, []int) {
	return file_api_gpt_gpt_proto_rawDescGZIP(), []int{1, 0, 0}
}

// The request message containing the bank's name and country.
type FindBankInformationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Country string `protobuf:"bytes,2,opt,name=country,proto3" json:"country,omitempty"`
}

func (x *FindBankInformationRequest) Reset() {
	*x = FindBankInformationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_gpt_gpt_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindBankInformationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindBankInformationRequest) ProtoMessage() {}

func (x *FindBankInformationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gpt_gpt_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindBankInformationRequest.ProtoReflect.Descriptor instead.
func (*FindBankInformationRequest) Descriptor() ([]byte, []int) {
	return file_api_gpt_gpt_proto_rawDescGZIP(), []int{0}
}

func (x *FindBankInformationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FindBankInformationRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

// The response message containing the bank's details.
type FindBankInformationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url         string                                  `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Name        string                                  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Country     string                                  `protobuf:"bytes,3,opt,name=country,proto3" json:"country,omitempty"`
	LogoLink    string                                  `protobuf:"bytes,4,opt,name=logo_link,json=logoLink,proto3" json:"logo_link,omitempty"`
	FaviconLink string                                  `protobuf:"bytes,5,opt,name=favicon_link,json=faviconLink,proto3" json:"favicon_link,omitempty"`
	Address     string                                  `protobuf:"bytes,6,opt,name=address,proto3" json:"address,omitempty"`
	Contacts    []*FindBankInformationResponse_Contacts `protobuf:"bytes,7,rep,name=contacts,proto3" json:"contacts,omitempty"` // List of contacts
}

func (x *FindBankInformationResponse) Reset() {
	*x = FindBankInformationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_gpt_gpt_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindBankInformationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindBankInformationResponse) ProtoMessage() {}

func (x *FindBankInformationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gpt_gpt_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindBankInformationResponse.ProtoReflect.Descriptor instead.
func (*FindBankInformationResponse) Descriptor() ([]byte, []int) {
	return file_api_gpt_gpt_proto_rawDescGZIP(), []int{1}
}

func (x *FindBankInformationResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *FindBankInformationResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FindBankInformationResponse) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *FindBankInformationResponse) GetLogoLink() string {
	if x != nil {
		return x.LogoLink
	}
	return ""
}

func (x *FindBankInformationResponse) GetFaviconLink() string {
	if x != nil {
		return x.FaviconLink
	}
	return ""
}

func (x *FindBankInformationResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *FindBankInformationResponse) GetContacts() []*FindBankInformationResponse_Contacts {
	if x != nil {
		return x.Contacts
	}
	return nil
}

type FindBankInformationResponse_Contacts struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type        FindBankInformationResponse_Contacts_Type `protobuf:"varint,1,opt,name=type,proto3,enum=api.bankinfo.FindBankInformationResponse_Contacts_Type" json:"type,omitempty"`
	Description string                                    `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"` // Description about the contact's department
	Value       string                                    `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`             // Contact details
}

func (x *FindBankInformationResponse_Contacts) Reset() {
	*x = FindBankInformationResponse_Contacts{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_gpt_gpt_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindBankInformationResponse_Contacts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindBankInformationResponse_Contacts) ProtoMessage() {}

func (x *FindBankInformationResponse_Contacts) ProtoReflect() protoreflect.Message {
	mi := &file_api_gpt_gpt_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindBankInformationResponse_Contacts.ProtoReflect.Descriptor instead.
func (*FindBankInformationResponse_Contacts) Descriptor() ([]byte, []int) {
	return file_api_gpt_gpt_proto_rawDescGZIP(), []int{1, 0}
}

func (x *FindBankInformationResponse_Contacts) GetType() FindBankInformationResponse_Contacts_Type {
	if x != nil {
		return x.Type
	}
	return FindBankInformationResponse_Contacts_PHONE
}

func (x *FindBankInformationResponse_Contacts) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FindBankInformationResponse_Contacts) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_api_gpt_gpt_proto protoreflect.FileDescriptor

var file_api_gpt_gpt_proto_rawDesc = []byte{
	0x0a, 0x11, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x70, 0x74, 0x2f, 0x67, 0x70, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x61, 0x70, 0x69, 0x2e, 0x62, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x66,
	0x6f, 0x22, 0x4a, 0x0a, 0x1a, 0x46, 0x69, 0x6e, 0x64, 0x42, 0x61, 0x6e, 0x6b, 0x49, 0x6e, 0x66,
	0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x22, 0xb7, 0x03,
	0x0a, 0x1b, 0x46, 0x69, 0x6e, 0x64, 0x42, 0x61, 0x6e, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x1b, 0x0a,
	0x09, 0x6c, 0x6f, 0x67, 0x6f, 0x5f, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x6c, 0x6f, 0x67, 0x6f, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x21, 0x0a, 0x0c, 0x66, 0x61,
	0x76, 0x69, 0x63, 0x6f, 0x6e, 0x5f, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x66, 0x61, 0x76, 0x69, 0x63, 0x6f, 0x6e, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x18, 0x0a,
	0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x4e, 0x0a, 0x08, 0x63, 0x6f, 0x6e, 0x74, 0x61,
	0x63, 0x74, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x32, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x62, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x42, 0x61, 0x6e,
	0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x73, 0x52, 0x08, 0x63,
	0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x73, 0x1a, 0xad, 0x01, 0x0a, 0x08, 0x43, 0x6f, 0x6e, 0x74,
	0x61, 0x63, 0x74, 0x73, 0x12, 0x4b, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x37, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x62, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x66,
	0x6f, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x42, 0x61, 0x6e, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x43, 0x6f,
	0x6e, 0x74, 0x61, 0x63, 0x74, 0x73, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x1c, 0x0a, 0x04, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x09, 0x0a, 0x05, 0x50, 0x48, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05,
	0x45, 0x4d, 0x41, 0x49, 0x4c, 0x10, 0x01, 0x32, 0x78, 0x0a, 0x0a, 0x47, 0x70, 0x74, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x6a, 0x0a, 0x13, 0x46, 0x69, 0x6e, 0x64, 0x42, 0x61, 0x6e,
	0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x28, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x62, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x46, 0x69, 0x6e, 0x64,
	0x42, 0x61, 0x6e, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x62, 0x61, 0x6e,
	0x6b, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x42, 0x61, 0x6e, 0x6b, 0x49, 0x6e,
	0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x30, 0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x2d, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2f,
	0x67, 0x70, 0x74, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x67, 0x70, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_gpt_gpt_proto_rawDescOnce sync.Once
	file_api_gpt_gpt_proto_rawDescData = file_api_gpt_gpt_proto_rawDesc
)

func file_api_gpt_gpt_proto_rawDescGZIP() []byte {
	file_api_gpt_gpt_proto_rawDescOnce.Do(func() {
		file_api_gpt_gpt_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_gpt_gpt_proto_rawDescData)
	})
	return file_api_gpt_gpt_proto_rawDescData
}

var file_api_gpt_gpt_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_gpt_gpt_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_gpt_gpt_proto_goTypes = []interface{}{
	(FindBankInformationResponse_Contacts_Type)(0), // 0: api.bankinfo.FindBankInformationResponse.Contacts.Type
	(*FindBankInformationRequest)(nil),             // 1: api.bankinfo.FindBankInformationRequest
	(*FindBankInformationResponse)(nil),            // 2: api.bankinfo.FindBankInformationResponse
	(*FindBankInformationResponse_Contacts)(nil),   // 3: api.bankinfo.FindBankInformationResponse.Contacts
}
var file_api_gpt_gpt_proto_depIdxs = []int32{
	3, // 0: api.bankinfo.FindBankInformationResponse.contacts:type_name -> api.bankinfo.FindBankInformationResponse.Contacts
	0, // 1: api.bankinfo.FindBankInformationResponse.Contacts.type:type_name -> api.bankinfo.FindBankInformationResponse.Contacts.Type
	1, // 2: api.bankinfo.GptService.FindBankInformation:input_type -> api.bankinfo.FindBankInformationRequest
	2, // 3: api.bankinfo.GptService.FindBankInformation:output_type -> api.bankinfo.FindBankInformationResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_gpt_gpt_proto_init() }
func file_api_gpt_gpt_proto_init() {
	if File_api_gpt_gpt_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_gpt_gpt_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindBankInformationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_gpt_gpt_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindBankInformationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_gpt_gpt_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindBankInformationResponse_Contacts); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_gpt_gpt_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_gpt_gpt_proto_goTypes,
		DependencyIndexes: file_api_gpt_gpt_proto_depIdxs,
		EnumInfos:         file_api_gpt_gpt_proto_enumTypes,
		MessageInfos:      file_api_gpt_gpt_proto_msgTypes,
	}.Build()
	File_api_gpt_gpt_proto = out.File
	file_api_gpt_gpt_proto_rawDesc = nil
	file_api_gpt_gpt_proto_goTypes = nil
	file_api_gpt_gpt_proto_depIdxs = nil
}
